### PR TITLE
Update Router.fs

### PR DESCRIPTION
**Pull request by kerams**
Add a navigate overload taking HistoryMode and string array. HistoryMode needs to come first, otherwise implicit ParamArray construction does not work.

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Hello @kerams, this an interesting addition but it breaks the consistency with the rest of the overloads because all of them end with the history mode. How about adding separate overloads for one string, two strings etc. (If they are not already implemented)

**Comment by kerams** [comment]
It could be the last parameter, but then ParamArray needs to be dropped. The problem is that right now I need string * string * int * string * mode with more overloads in the future. I felt like adding highly specific overloads like this would just unnecessarily clutter the API, since at the end of the day, you can always convert your parameters to string array.

**Comment by kerams** [comment]
Alternatively, if Router.nav was public, you could bypass Router.navigate for more complex cases like this.

**Comment by Zaid-Ajaj** [comment]
I am trying to avoid conversion code in user applications, in your case I would actually just add that specific overload because the library already adds a lot of them

**Comment by kerams** [comment]
Do you want me to add all queryString/mode combinations or just the one overload?

**Comment by Zaid-Ajaj** [comment]
That would be great if you feel like it :pray: otherwise just the overload you need and I will do the rest :)

**Comment by kerams** [comment]
Does this look good?

**Comment by Zaid-Ajaj** [comment]
Yeah awesome! I have added and published your changes as of v1.4 :fire:

**Pull request merged**
