### PR TITLE
Add support for path based routes

### PR DESCRIPTION
**Pull request by marcpiechura**
@Zaid-Ajaj  here is a first try, let me know what you think. 

1eZu4BsZAI

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Looks good @marcpiechura but I am not a big fan of the `navigateP` overloads. I would rather have this defined globally on router level instead of per `Cmd` 
```fs
Router.router [
  Router.onUrlChanged (UrlChanged >> dispatch)
  Router.application currentPage
  Router.mode.path // or Router.mode.hash
]
```
When mounting the router component, set this input `Router.mode` somewhere global (in `window["Router.mode"]`?) and when navigating, Router.nav will inspect this global variable and decide whether or not to use path or hash for the new route. What do you think? 

I know the internals might *not* be be as pretty because of a global variable but it makes for a nice dev experience if you want to change your routing from using hash or path modes.

**Comment by marcpiechura** [comment]
@Zaid-Ajaj good idea. I've changed the code and now one can use `Router.hashMode` or `Router.pathMode` as option. I wasn't sure how I would build something like `Router.mode.hash`, so I've simply used a single property and I haven't found a simple way to attach a property to the `window`, so I've simply added a internal mutable field.

**Comment by marcpiechura** [comment]
@Zaid-Ajaj good idea. I've changed the code and now one can use `Router.hashMode` or `Router.pathMode` as option. I wasn't sure how I would build something like `Router.mode.hash`, so I've simply used a single property and I haven't found a simple way to attach a property to the `window`, so I've simply added a internal mutable field.

**Comment by Zaid-Ajaj** [comment]
Awesome work @marcpiechura I have modified the code just a bit to update the internal variable when the component updates it's props (say when someone dynamically chooses the route mode and updates in runtime) I also added a nice overload for application which allows to take a list of child elements:
```fs
Router.router [
    Router.onUrlChanged (UrlChanged >> dispatch)
    Router.pathMode
    Router.application [
        Html.div [
            Html.h1 "Using the router"
        ]
    ]
]
```
Published a package as of v1.5.0 :rocket: can you take it for a spin when it is available on Nuget? Let me know how it goes

**Comment by Zaid-Ajaj** [comment]
Scratch that, can you go for v1.5.1 missed a property name there 😅

**Comment by marcpiechura** [comment]
@Zaid-Ajaj works like a charm 👍

**Pull request merged**
